repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        args: ["--preview", "--line-length", "79", "--target-version", "py312"]
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports, --in-place ]
  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        args: [ "--ignore=E203,W503,E501,E704" ]
  - repo: https://github.com/Tesla2000/vulture
    rev: v0.0.4
    hooks:
      - id: vulture
        args:
          [
            ".",
            "--exclude",
            ".venv,venv,tests,docs",
            "--ignore-attributes-for-classes=.*",
            "--ignore-decorators=@app.*,@pytest.fixture,@property,@model_validator,@field_serializer,@field_validator",
            "--ignore-names=Meta,__dict__,cli_cmd,annotation,ExternalModifier,side_effect,return_value",
             "--extra-sys-path=.venv/lib/python3.12/site-packages,.",
          ]
        stages: [ pre-commit ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.1
    hooks:
      - id: mypy
        exclude: (^tests/|\.pyi$)
        additional_dependencies:
           - pydantic
           - pydantic-settings
           - libcst
           - types-PyYAML
           - autoimport
           - subclass_getter
        args: [ --strict, --config-file, pyproject.toml]
  - repo: https://github.com/Tesla2000/any-hook
    rev: v3.2.0
    hooks:
      - id: any-hook
        args: [--modifiers, '[{"type": "remove-f-prefix"},{"type": "open-to-path"},{"type": "any-to-object"},{"type": "local-imports"},{"type": "check-untracked", "directories": ["any_hook","tests"]},{"type":"pydantic-config-to-model-config"},{"type":"pydantic-v1-to-v2"},{"type":"str-enum-inheritance"},{"type":"forbidden-functions","forbidden_functions":["hasattr","getattr"]},{"type":"forbidden-functions","forbidden_functions":["print"],"excluded_paths":["any_hook/files_modifiers/output/stdout.py","any_hook/_transaction.py","any_hook/files_modifiers/__init__.py","any_hook/files_modifiers/__init__.py"]},{"type":"utcnow-to-datetime-now"},{"type":"len-as-bool"},{"type":"typing-to-builtin"}]']
